% help_with_neuralynx_config

nchannels=4*14;
chan_num=0:nchannels;
clc
for i=1:nchannels
fprintf(['#Acquisition Entity creation and setup for: "CSC',num2str(i),'" \r',...
'-CreateCscAcqEnt "CSC',num2str(i),'" "AcqSystem1" \r',...
'-SetAcqEntProcessingEnabled "CSC',num2str(i),'" True \r',...
'-SetChannelNumber "CSC',num2str(i),'" ',num2str(chan_num(i)),' \r',...
'-SetAcqEntReference "CSC',num2str(i),'" 35000001 \r',...
'-SetInputRange "CSC',num2str(i),'" 10000 \r',...
'-SetSubSamplingInterleave "CSC',num2str(i),'" 1 \r',...
'-SetDspLowCutFilterEnabled "CSC',num2str(i),'" True \r',...
'-SetDspLowCutFrequency "CSC',num2str(i),'" 0.1 \r',...
'-SetDspLowCutNumberTaps "CSC',num2str(i),'" 0 \r',...
'-SetDspHighCutFilterEnabled "CSC',num2str(i),'" True \r',...
'-SetDspHighCutFrequency "CSC',num2str(i),'" 9000 \r',...
'-SetDspHighCutNumberTaps "CSC',num2str(i),'" 32 \r',...
'-SetInputInverted "CSC',num2str(i),'" True \r',...
'-SetDiskWriteEnabled "CSC',num2str(i),'" True \r',...
'-SetNetComDataBufferingEnabled "CSC',num2str(i),'" False \r',...
'-SetNetComDataBufferSize "CSC',num2str(i),'" 3000 \r'])
fprintf('\r')
fprintf('\r')
end

%%
clc
for i=1:nchannels
fprintf(['-AddPlot "Time Window 1" "CSC',num2str(i),'" \r',...
'-SetPlotEnabled "Time Window 1" "CSC',num2str(i),'" "True" \r',...
'-SetTimePlotZoomFactor "Time Window 1" "CSC',num2str(i),'" 8 \r'])
end
%%