% help_with_neuralynx_config
number_of_tetrodes=16;

nchannels=4*number_of_tetrodes;
chan_num=0:nchannels;

%% create acquisition of channels
clc
for i=1:nchannels
    fprintf(['#Acquisition Entity creation and setup for: "CSC',num2str(i),'" \r',...
        '-CreateCscAcqEnt "CSC',num2str(i),'" "AcqSystem1" \r',...
        '-SetAcqEntProcessingEnabled "CSC',num2str(i),'" True \r',...
        '-SetChannelNumber "CSC',num2str(i),'" ',num2str(chan_num(i)),' \r',...
        '-SetAcqEntReference "CSC',num2str(i),'" 35000001 \r',...
        '-SetInputRange "CSC',num2str(i),'" 10000 \r',...
        '-SetSubSamplingInterleave "CSC',num2str(i),'" 1 \r',...
        '-SetDspLowCutFilterEnabled "CSC',num2str(i),'" True \r',...
        '-SetDspLowCutFrequency "CSC',num2str(i),'" 0.1 \r',...
        '-SetDspLowCutNumberTaps "CSC',num2str(i),'" 0 \r',...
        '-SetDspHighCutFilterEnabled "CSC',num2str(i),'" True \r',...
        '-SetDspHighCutFrequency "CSC',num2str(i),'" 9000 \r',...
        '-SetDspHighCutNumberTaps "CSC',num2str(i),'" 32 \r',...
        '-SetInputInverted "CSC',num2str(i),'" True \r',...
        '-SetDiskWriteEnabled "CSC',num2str(i),'" True \r',...
        '-SetNetComDataBufferingEnabled "CSC',num2str(i),'" False \r',...
        '-SetNetComDataBufferSize "CSC',num2str(i),'" 3000 \r'])
    fprintf('\r')
    fprintf('\r')
end

%% add plots for each channel
clc
for i=1:nchannels
    fprintf(['-AddPlot "Time Window 1" "CSC',num2str(i),'" \r',...
        '-SetPlotEnabled "Time Window 1" "CSC',num2str(i),'" "True" \r',...
        '-SetTimePlotZoomFactor "Time Window 1" "CSC',num2str(i),'" 8 \r'])
end

%% create acquisition of tetrodes
clc
for i=1:number_of_tetrodes
    fprintf(['#Acquisition Entity creation and setup for: "TT',num2str(i),'" \r',...
        '-CreateSpikeAcqEnt "TT',num2str(i),'" "AcqSystem1" 4 \r',...
        '-SetAcqEntProcessingEnabled "TT',num2str(i),'" True \r',...
        '-SetChannelNumber "TT',num2str(i),'" ', num2str((i-1)*4:(i-1)*4+3), '\r',...
        '-SetAcqEntReference "TT',num2str(i),'" 35000001 \r',...
        '-SetInputRange "TT',num2str(i),'" 500 500 500 500 \r',...
        '-SetSubSamplingInterleave "TT',num2str(i),'" 1 \r',...
        '-SetDspLowCutFilterEnabled "TT',num2str(i),'" True \r',...
        '-SetDspLowCutFrequency "TT',num2str(i),'" 600 \r',...
        '-SetDspLowCutNumberTaps "TT',num2str(i),'" 64 \r',...
        '-SetDspHighCutFilterEnabled "TT',num2str(i),'" True \r',...
        '-SetDspHighCutFrequency "TT',num2str(i),'" 6000 \r',...
        '-SetDspHighCutNumberTaps "TT',num2str(i),'" 32 \r',...
        '-SetInputInverted "TT',num2str(i),'" True \r',...
        '-SetDiskWriteEnabled "TT',num2str(i),'" True \r',...
        '-SetNetComDataBufferingEnabled "TT',num2str(i),'" True \r',...
        '-SetNetComDataBufferSize "TT',num2str(i),'" 3000 \r',...
        '-SetSpikeThreshold "TT',num2str(i),'" 40 40 40 40 \r',...
        '-SetSpikeDetectionType "TT',num2str(i),'" Threshold \r',...
        '-SetSpikeSlope "TT',num2str(i),'" 0 25 160 \r',...
        '-SetSpikeSlope "TT',num2str(i),'" 1 25 160 \r',...
        '-SetSpikeSlope "TT',num2str(i),'" 2 25 160 \r',...
        '-SetSpikeSlope "TT',num2str(i),'" 3 25 160 \r',...
        '-SetSpikeDualThresholding "TT',num2str(i),'" False \r',...
        '-SetSpikeRetriggerTime "TT',num2str(i),'" 750 \r',...
        '-SetSpikeAlignmentPoint "TT',num2str(i),'" 8 \r',...
        '-SetSubChannelEnabled "TT',num2str(i),'" 0 True \r',...
        '-SetSubChannelEnabled "TT',num2str(i),'" 1 True \r',...
        '-SetSubChannelEnabled "TT',num2str(i),'" 2 True \r',...
        '-SetSubChannelEnabled "TT',num2str(i),'" 3 True \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Peak 0 0 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Peak 1 1 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Peak 2 2 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Peak 3 3 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Valley 4 0 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Valley 5 1 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Valley 6 2 0 31 \r',...
        '-SetWaveformFeature "TT',num2str(i),'" Valley 7 3 0 31 \r'])
    fprintf('\r')
    fprintf('\r')
end

%% set up plot for tetrodes
clc
fprintf(['# Plot Window Setup for Spike Window 1 \r',...
    '-CreatePlotWindow Spike "Spike Window 1" \r',...
    '-SetPlotWindowPlotType "Spike Window 1" WaveformFeature \r',...
    '-SetPlotWindowShowIcons "Spike Window 1" true \r',...
    '-SetPlotWindowShowTextValues "Spike Window 1" true \r',...
    '-SetPlotWindowNumberFeaturePlotsMaximizedView "Spike Window 1" 1 \r',...
    '-SetPlotWindowNumberFeaturePlotsNormalView "Spike Window 1" 1 \r',...
    '-SetPlotWindowPosition "Spike Window 1" 751 2 929 1004 \r',...
    '-SetPlotWindowOverlay "Spike Window 1" false \r',...
    '-SetPlotWindowShowTitleBar "Spike Window 1" true \r',...
    '-SetPlotWindowFrozen "Spike Window 1" false \r',...
    '# Plot addition and setup for Spike Window 1 \r'])
for i=1:number_of_tetrodes
    fprintf(['-AddPlot "Spike Window 1" "TT',num2str(i),'" \r',...
        '-SetPlotEnabled "Spike Window 1" "TT',num2str(i),'" "True" \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 0 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 1 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 2 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 3 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 4 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 5 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 6 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 7 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 8 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 9 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 10 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 11 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 12 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 13 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 14 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 15 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 16 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 17 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 18 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 19 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 20 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 21 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 22 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 23 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 24 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 25 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 26 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 27 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 28 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 29 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 30 on \r',...
        '-SetClusterDisplay "Spike Window 1" "TT',num2str(i),'" 31 on \r',...
        '-SetFeaturePlotSources "Spike Window 1" "TT',num2str(i),'" 0 0 1 \r',...
        '-SetFeaturePlotView "Spike Window 1" "TT',num2str(i),'" 0 -3000 32767 32767 -3000'])
    fprintf('\r')
    fprintf('\r')
end