path = '/Users/bjclark/Desktop/Dropbox/place cell analysis/Raw Data/RH026 10-28-2013/Spike Timestamps';
ReadData = FindFiles('TT2- RH_SS_09.txt', 'StartingDirectory', path);


    %load spike train data from .ts file outputs
    spikes10u = dlmread(ReadData{1},'\t',0,0); %load spike data which is in 10s of usec
    spikes = spikes10u./10; %convert spikes to msec
    
    %Generate Autocorrelation of spike train
    [iAutoCorr, Times] = AutoCorr(spikes, 1, 500);
    
    %smooth autocorrelation curve and normalize to 1
    sAutoCorr = runline(iAutoCorr, 10, 1);
    sAutoCorr(sAutoCorr < 0) = [0]; %make negative numbers=0 (they are generated by runline)
    maxsAutoCorr = max(sAutoCorr);
    normAutoCorr = sAutoCorr./maxsAutoCorr;
    
    %calculate a theta ratio (first trough/second peak)
    minCorr = min(normAutoCorr(25:105));
    maxCorr = max(normAutoCorr(95:175));
    ThetaRatio = (maxCorr-minCorr);
%     
%     %fit a sinusoid to the autocorrelation
%     xSinu=[0.00628318:0.00628318:3.14159]';
%     opts = fitoptions('Method', 'NonlinearLeastSquares');
%     opts.Lower = [-Inf -Inf -Inf 4];
%     opts.StartPoint = [0 0 0 7];
%     opts.Upper = [Inf Inf Inf 12];
%     [f, G]=fit(xSinu,normAutoCorr,'fourier1',opts);
%     Frequency=f.w;
%     Fit=G.rsquare;
    
    %plot the autocorrelation
    fig1 = area(normAutoCorr,'facecolor','k'); %smoothed and normalized autocorrelation
    axis square tight
    box off
%     
%     [filepath, filename] = fileparts(ReadData{1});
%     saveas(fig1,[filepath filesep filename 'theta.jpg']);
%     save([filepath filesep filename '_AutoCorrTheta.mat']);
%     close all
