function hosadem
%HOSADEM Set up HOSA command-line demos for the MATLAB Demo.

% Copyright (c) 1991-2001 by United Signals & Systems, Inc. 
% $Revision: 1.6 $  $Date: 1999/01/04 21:33:38 $

%     RESTRICTED RIGHTS LEGEND
% Use, duplication, or disclosure by the Government is subject to
% restrictions as set forth in subparagraph (c) (1) (ii) of the
% Rights in Technical Data and Computer Software clause of DFARS
% 252.227-7013.
% Manufacturer: United Signals & Systems, Inc., P.O. Box 2374,
% Culver City, California 90231.
%
%  This material may be reproduced by or for the U.S. Government pursuant
%  to the copyright license under the clause at DFARS 252.227-7013.


labelList = str2mat( ...
    'Definitions/Tutorial',...
    'Cumulants/Polyspectra',...
    'Gaussianity-Linearity Tests',...
    'Parametric Linear Sys Id',...
    'Non-Parametric Linear Sys Id',...
    'Quadratic Phase Coupling',...
    'Volterra Systems',...
    'Harmonics in Noise',...
    'Time-Delay Estimation',...
    'Direction of Arrival',...
    'Adaptive Parameter Estimation',...
    'Time-Frequency Distributions');

nameList = str2mat( ...
          'demtut',...
          'dembisp',...
          'demgltst',...
          'demarma',...
          'demnpsi',...
          'demqpc',...
          'demvolt',...
          'demharm',...
          'demtde',...
          'demdoa',...
          'demadapt',...
          'demtfd');

figureFlagList = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

cmdlnwin(labelList, nameList, figureFlagList);