% Combine_track_cylinder

tbl1 = importfile('F:\Projects\PAE_PlaceCell\Rdata_pae_sfn2019_lineartrack.csv');
tbl2 = importfile('F:\Projects\PAE_PlaceCell\Rdata_pae_sfn2019_cylinder.csv');

track_cylinder = [tbl1;tbl2];
track_cylinder.mazetype = [cellstr(repmat('track',size(tbl1,1),1));cellstr(repmat('cylinder',size(tbl2,1),1))];

writetable(track_cylinder,'F:\Projects\PAE_PlaceCell\Rdata_pae_sfn2019_track_cylinder.csv')

% figure
% idx1 = contains(track_cylinder.mazetype,'track') & contains(track_cylinder.area,"ca1") & contains(track_cylinder.group,"control");
% idx2 = contains(track_cylinder.mazetype,'cylinder') & contains(track_cylinder.area,"ca1") & contains(track_cylinder.group,"control");
% 
% AllStatsca1=stat_plot(track_cylinder.InformationContent(idx1),track_cylinder.InformationContent(idx2),{'Sacc','PAE'},{'Information'})
% hold on
% idx1 = contains(track_cylinder.mazetype,'track') & contains(track_cylinder.area,"ca1") & contains(track_cylinder.group,"pae");
% idx2 = contains(track_cylinder.mazetype,'cylinder') & contains(track_cylinder.area,"ca1") & contains(track_cylinder.group,"pae");
% 
% AllStatsca1=stat_plot(track_cylinder.InformationContent(idx1),track_cylinder.InformationContent(idx2),{'Sacc','PAE'},{'Information'})


function Rdatapaesfn2019cylinder1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RDATAPAESFN2019CYLINDER1 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  RDATAPAESFN2019CYLINDER1 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Rdatapaesfn2019cylinder1 = importfile("F:\Projects\PAE_PlaceCell\Rdata_pae_sfn2019_cylinder.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Oct-2019 19:01:47

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 71);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["InformationContent", "Coherence", "Sparsity", "PeakRate", "OverallFiringRate", "Field2Wall", "FieldWidth", "nSpikes", "mean_vector_length", "preferred_Direction", "Direct_infoContent", "DirectionalityIndex", "PhPrecessSlope", "PH_RSquared", "lapPhPrecessSlope", "lapPH_RSquared", "PhlapCorrelation", "lapPhaseOffset", "PhcircLinCorr", "Phpval", "slopeCpU", "phaseOffset", "MeanThetaFreq", "MeanThetaPow", "Displacement", "infieldFR", "outfieldFR", "borderScore", "E", "NumbActiveBins", "DisplacementCorr", "SpeedScore", "IntraTrialStability", "nspikesinfield", "ThetaPhaseLockR", "ThetaPhaselockPval", "thetaindex", "thetapeak", "LRatio", "ShortISI", "IsolationDistance", "NumberOfSpikes", "WaveformPeak", "WaveformValley", "spikewidth", "halfwidth", "peak2valleyratio", "peak2valleyslope", "SpikeAmplitude", "temporalstability", "nlaps", "rateoverlap", "fieldoverlap", "lap_perm_stability", "stabilityoverlaps", "meanstability", "spatialcorrelation", "egomod", "bordermod", "burstIdx", "corrected_r", "corrected_dic", "corrected_info_content", "corrected_sparsity", "correction_fit", "runningdir", "session", "tt", "cell", "area", "group"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "double", "string", "string"];
opts = setvaropts(opts, [67, 68, 70, 71], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [67, 68, 70, 71], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Rdatapaesfn2019cylinder1 = readtable(filename, opts);

end